[package]
name = "homomorphic_actors"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"]}
sids = "0.3.2"
tfhe = { version = "1.2.0", features = ["boolean", "shortint", "integer"] }
env_logger = "0.11.8"
log = {version = "0.4", features = ["kv"]}
